### ISSUE TITLE
React native integration.

### ISSUE THREAD

**Issue by GTDev87** [styled-components/elm-styled#15]
This is the most nice to have thing ever but it would be sweet if this package could work with react native the same way styled components does.  It could then coordinate with the package https://github.com/ohanhi/elm-native-ui

**Comment by k15a** [comment]
Hey, thank you for the interest but currently I have lost interest developing this package further because it relies on native code which the elm package repository only allows in special core packages. Unfortunately there is no way to publish this package currently. Hope you understand that and thank you for the kind words :)
